version: '3.8'

services:
  db: 
    image: mongo:latest
    container_name: mongodb_mflix_container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - ./db/.env
    networks:
      - booksntwrk
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db
  
networks: 
  ntwrk: 
    driver: bridge

volumes:
  mongodb_data_container:
    driver: local