version: '3.8'

services:
  db: 
    image: mongo:latest
    container_name: mongodb_mflix_container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - ntwrk
    ports:
      - "27018:27017"
    volumes:
      - ./db/import:/tmp/import
  app: 
    build: ./app
    container_name: app_mflix
    networks:
      - ntwrk
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://user:userpassword@db:27017/mflix
      - MONGO_INITDB_DATABASE=mflix
      - MONGO_INITDB_COLLECTION=movies
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
  
networks: 
  ntwrk: 
    driver: bridge