version: '3.8'

services:
  db: 
    image: mongo
    env_file:
      - ./db/.env
    networks:
      - ntwrk
    ports:
      - "27018:27017"
    volumes:
      - ./db/import:/tmp/import
  app: 
    build: ./app
    container_name: app_mflix
    networks:
      - ntwrk
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://admin:adminpassword@db:27017
      - MONGO_INITDB_DATABASE=mflix
      - MONGO_INITDB_COLLECTION=movies
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=userpassword
    ports:
      - "8080:80"
  
networks: 
  ntwrk: 
    driver: bridge